# Generated by Django 4.1.2 on 2022-12-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0003_alter_note_valeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveau',
            name='matieres',
            field=models.ManyToManyField(to='Notes.matiere'),
        ),
    ]
