# Generated by Django 4.1.2 on 2022-12-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0004_niveau_matieres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='matieres',
            field=models.ManyToManyField(null=True, to='Notes.matiere', verbose_name='Matières appartenant au niveau sélectionné '),
        ),
    ]
