# Generated by Django 4.1.2 on 2022-12-12 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notes', '0007_alter_eleve_matieres'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='matieres',
            field=models.ManyToManyField(blank=True, to='Notes.matiere', verbose_name='Matières appartenant au niveau sélectionné '),
        ),
    ]
